name: Build and Publish Node Addon (Windows Only)

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            platform: win32
            arch: ia32
            target: i686-pc-windows-msvc

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies
        run: npm ci

      - name: Build native addon
        run: npx napi build --platform --release --target ${{ matrix.target }}

      - name: Run additional build scripts
        run: |
          node build.js
          node convert.js

      - name: Show all .node files (debug)
        run: dir /s /b *.node || echo "No .node files found"
        shell: cmd

      - name: Copy .node files to zippy-encyptor
        run: |
          if not exist zippy-encyptor mkdir zippy-encyptor
          for %%f in (encryptor.*.node) do copy "%%f" zippy-encyptor\
        shell: cmd

      - name: List files in zippy-encyptor
        run: |
          echo Files in zippy-encyptor:
          dir zippy-encyptor
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.built-file.outputs.name }}
          path: zippy-encyptor/${{ steps.built-file.outputs.name }}
          retention-days: 7
