name: Build and Publish Node Addon

on:
  workflow_dispatch:

permissions:
  contents: write # 允许写入代码库内容
  packages: write # 允许写入包
  id-token: write # 允许写入 ID 令牌
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            platform: linux
            arch: arm
            target: armv7-unknown-linux-gnueabihf
          - os: macos-latest
            platform: darwin
            arch: x64
            target: x86_64-apple-darwin
          - os: macos-latest
            platform: darwin
            arch: arm64
            target: aarch64-apple-darwin
          - os: windows-latest
            platform: win32
            arch: x64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            platform: win32
            arch: ia32
            target: i686-pc-windows-msvc
          - os: ubuntu-latest
            platform: android
            arch: arm64
            target: aarch64-linux-android
          - os: ubuntu-latest
            platform: android
            arch: arm
            target: armv7-linux-androideabi

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install cross-compilation toolchain for aarch64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install cross-compilation toolchain for armv7
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Install dependencies
        run: npm ci

      - name: Build native addon for specific target
        run: npx napi build --platform --release --target ${{ matrix.target }}

      - name: List and copy .node files
        if: matrix.os != 'windows-latest'
        run: |
          for file in *.node; do
            if [ -f "$file" ]; then
              cp "$file" "zippy-encryptor/$file"
              echo "NODE_FILENAME=$file" >> $GITHUB_ENV
            fi
          done
        shell: bash

      - name: List and copy .node files for Windows
        if: matrix.os == 'windows-latest'
        run: |
          for %%i in (*.node) do (
            copy "%%i" "zippy-encryptor\"
            echo NODE_FILENAME=%%~nxi>> %GITHUB_ENV%
          )
        shell: cmd

      - name: List files in zippy-encryptor directory (before upload)
        run: |
          echo "Files in zippy-encryptor directory:"
          if [ "$RUNNER_OS" == "Windows" ]; then
            dir zippy-encryptor
          else
            ls -la zippy-encryptor/
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NODE_FILENAME || format('node-addon-{0}-{1}', matrix.platform, matrix.arch) }}
          path: zippy-encryptor/
          retention-days: 7
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Copy artifacts to zippy-encryptor
        run: |
          echo "Downloaded artifacts:"
          find downloaded-artifacts -type f -name "*.node" | sort

          # Copy all .node files to zippy-encryptor directory
          find downloaded-artifacts -type f -name "*.node" -exec cp {} zippy-encryptor/ \;

          echo "Contents of zippy-encryptor directory:"
          ls -la zippy-encryptor/

      - name: Run build scripts
        run: |
          node build.js
          node convert.js

      - name: Update version and publish
        run: |
          cd zippy-encryptor
          npm version patch
          npm version patch
          # 获取新版本号
          VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag and commit version update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update version to ${{ env.PACKAGE_VERSION }}"
          git tag "v${{ env.PACKAGE_VERSION }}"
          git push
          git push origin "v${{ env.PACKAGE_VERSION }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.PACKAGE_VERSION }}"
          name: "Release v${{ env.PACKAGE_VERSION }}"
          body: |
            ## Release Notes
            - Version: ${{ env.PACKAGE_VERSION }}
          files: zippy-encryptor/*.node
