/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 加密文件 - 适用于小到中等大小的文件 */
export declare function encryptFile(algorithm: string, key: Buffer, inputPath: string, outputPath: string): object
/** 解密文件 - 适用于小到中等大小的文件 */
export declare function decryptFile(algorithm: string, key: Buffer, inputPath: string, outputPath: string): object
/** 分片加密文件 - 用于超大文件，带有分片处理功能 */
export declare function chunkEncryptFile(algorithm: string, key: Buffer, inputPath: string, outputPath: string, chunkSizeMb: number): object
/** 分片解密文件 - 用于超大文件，处理分片加密的文件 */
export declare function chunkDecryptFile(algorithm: string, key: Buffer, inputPath: string, outputPath: string): object
/** 单个分片的解密 - 用于视频实时播放场景 */
export declare function decryptSingleChunk(algorithm: string, key: Buffer, inputPath: string, chunkIndex: number): Buffer
/** 获取分片加密文件的元数据 - 用于视频播放前获取文件信息 */
export declare function getChunkedFileMetadata(inputPath: string): object
/** 获取文件大小通用函数，用于测试文件操作 */
export declare function getFileSize(filePath: string): number
/** 计算文件的MD5哈希值 */
export declare function computeFileMd5(filePath: string): string
